apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-chall-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-chall-app
  template:
    metadata:
      labels:
        app: tech-chall-app
    spec:
      containers:
        - name: tech-chall-container
          image: gabitriferreira/tech-challenge-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATA_MONGODB_HOST
            - name: SPRING_DATA_MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATA_MONGODB_PORT
            - name: SPRING_DATA_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATA_MONGODB_DATABASE
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATA_MONGODB_USERNAME
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATA_MONGODB_PASSWORD
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"


              